version: '3.8'
services:

  frontend:
    image: trang_share_video/frontend
    container_name: trang_share_video_frontend
    restart: unless-stopped
    ports:
      - "2050:2050"
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    
    networks:
      - trang-prod-network

  backend:
    image: trang_share_video/backend
    container_name: trang_share_video_backend
    restart: unless-stopped
    ports:
      - "2070:2070"
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - trang-prod-network

networks:
  trang-prod-network:

